config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'fajna_strona', to: 'home#index'
  get 'about', to: 'home#about'
  get 'terms', to: 'home#terms'
  resources :ads

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'account', to: 'users#account'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :ads do
  post 'rate', on: :member
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
validates :title, :description, presence: true
validates :image, presence: true unless Rails.env.test?
belongs_to :user
has_many :ratings
mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :value, inclusion: { in: [-1, 1] }
  validates :user_id, uniqueness: {scope: :ad_id}
  belongs_to :user
  belongs_to :ad
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  validates :email, presence: true,
            format: { with: /\A([^@\s]+)@[a-z\d\-.]+\.[a-z]{2,}\z/i },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :first_name, :last_name, presence: true,
            length: {minimum: 2, maximum: 50}
has_secure_password
has_many :ads
has_many :ratings

def downcase_email
  email.downcase!
end

def full_name
  "#{first_name} #{last_name}"
end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
before_action :login_required, except: [:index, :show]
before_action :set_ad, only: [:edit, :update, :destroy]
def index
  @ads = Ad.all
end
def show
  @ad = Ad.find(params[:id])
  @rating = @ad.ratings.find_by(user: current_user)
end
def new
@ad = Ad.new
end
def edit
end
def create
@ad = Ad.new(ad_params)
@ad.user = current_user
if @ad.save
  flash[:success] = "Zamieszczono ogłoszenie!"
  redirect_to @ad
else
  flash.now[:danger] = "Nie można zamieścić ogłoszenia!"
  render :new
end
end
def update
if @ad.update(ad_params)
flash[:success] = "Zaktualizowano ogłoszenie!"
redirect_to @ad
else
flash.now[:danger] = "Nie można zaktualizować ogłoszenia!"
render :edit
end
end
def destroy
@ad.destroy
if @ad.destroy
  flash[:success] = "Usunięto zdjęcie!"
redirect_to ads_url
else
  flash[:danger] = "Nie można usunąć zdjęcia!"
  render :edit
end
end
def set_ad
  @ad = current_user.ads.find(params[:id])
end
def rate
  ad = Ad.find(params[:id])
  rating = ad.ratings.find_or_initialize_by(user: current_user)
  rating.value = params[:value]
  rating.save!
  flash[:success] = 'Ocena została zapisana.'
  redirect_to(:back)
end
private

def ad_params
  params.require(:ad).permit(:title, :description, :image)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthenticationHelper
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def terms
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login_user(user)
      flash[:success] = 'Zostałeś zalogowany.'
      redirect_to_target_or_root
    else
      flash.now[:danger] = 'Niepoprawny email lub hasło.'
      render :new
    end
end
  def destroy
    log_out
    flash[:success] = "Zostałeś wylogowany. "
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
require "recaptcha/rails"
class UsersController < ApplicationController
before_action :login_required, only: :account
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if !verify_recaptcha
  flash.now[:danger] = 'Uzupełnij reCAPTCHA.'
  render :new
  elsif @user.save
  login_user(@user)
  flash[:success] = 'Zostałeś zarejestrowany.'
  redirect_to_target_or_root
  else
  flash.now[:danger] = 'Nie można utworzyć konta użytkownika.'
  render :new
end
end

private
def user_params
params.require(:user).permit(
:email, :first_name, :last_name, :password, :password_confirmation
)

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
  def login_user(user)
    return_to = session[:return_to]
    reset_session
    session[:user_id] = user.id
    session[:return_to] = return_to
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !current_user.nil?
end
def log_out
reset_session
end

def login_required
  unless logged_in?
    store_target_location
    flash[:warning] = 'Zaloguj sie aby uzyskać dostęp.'
    redirect_to login_path
end
end

def redirect_to_target_or_root
redirect_to(session[:return_to] || root_path)
session[:return_to] = nil
end


private
def store_target_location
  session[:return_to] = request.url
end
end

app/helpers/form_errors_helper.rb
module FormErrorsHelper
  def error_message_for(object, field)
    return unless object.respond_to?(:errors) && object.errors.include?(field)
    error_messages = object.errors[field].join(', ')
    content_tag(:div, error_messages, class: 'form-error-message')
  end
end 

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for(@ad) do |f| %>
<div class="form-group">
<%= f.label :title, 'Tytuł' %>
<%= f.text_field :title, class: 'form-control', placeholder: 'Wpisz tytuł'%>
</div>
<div class="form-group">
<%= f.label :description, 'Opis' %>
<%= f.text_area :description, class: 'form-control', placeholder: 'Wpisz opis'%>
</div>
<div class="form-group">
<%= f.label :image, 'Plik zdjęcia' %>
<%= f.file_field :image, class: 'form-control', placeholder: 'Dodaj plik' %>
</div>
<div class="actions">
<%= f.submit 'Zapisz zdjęcie', class: 'btn btn-primary' %>
</div>
<% end %>
</div>
</div>

app/views/ads/_rating_form.html.erb
<%= button_to 'Podoba mi się', rate_ad_path(ad), params: { value: 1 } %>
<%= button_to 'Nie podoba mi się', rate_ad_path(ad), params: { value: - 1} %>
<% if rating %>
<p>
  Przyznałeś ocenę <%= rating.value %>
</p>
<% end %> 

app/views/ads/edit.html.erb
<% content_for :title, "Edycja zdjęcia" %>
<h1>Edycja zdjęcia</h1>
<%= render 'form', photo: @photo %>

app/views/ads/index.html.erb
<% content_for :title, 'Zdjęcia' %>
<h1>Ogłoszenia</h1>
<%= link_to "Dodaj zdjęcie", new_ad_path, class: 'btn btn-primary pull-right' %></tr>

<table class="table">
<thead>
<tr>
<th>Tytuł</th>
<th>Opis</th>
<th>Plik</th>
<th colspan="2"></th>
</tr>
</thead>
<tbody>
<% @ads.each do |ad| %>
<tr>
<td><%= link_to ad.title, ad_path(ad) %></td>
<td><%= ad.description %></td>
<td><%= image_tag ad.image_url, height: 50 %></td>
<% if ad.user == current_user %>
<td><%= link_to 'Edytuj', edit_ad_path(ad) %></td>
<td><%= link_to 'Usuń', ad_path(ad), method: :delete, data: { confirm: 'Na pewno chcesz usunąć ogłoszenie?' }%></td>
<% else %>
<td>
<td>
<% end %>
<% end %>

</tr>
</tbody>
</table>

app/views/ads/new.html.erb
<% content_for :title, "Nowe zdjęcie" %>
<h1>Nowe zdjęcie</h1>
<%= render 'form', photo: @photo %>

app/views/ads/show.html.erb
<%= render 'rating_form', ad: @ad, rating: @rating %>
<% content_for :title, @ad.title %>
<h1>
  <%= @ad.title %>
</h1>
<p>
  <strong>Opis:</strong>
  <%= @ad.description %>
</p>
<p>
<%= image_tag @ad.image_url, height: 50 %>
</p>
<p>
  <strong>Dodane przez: </strong>
  <%= "#{@ad.user.full_name}"%>
<p>

app/views/home/about.html.erb
<% content_for :title, "O nas" %>
<h1>Informacje o stronie</h1>
<p>
AdDash to na razie aplikacja tworzona podczas nauki frameworku Ruby on
Rails. W przyszłości będzie to jeden z największych portali stworzonych dla reklamodawców.
</p>

app/views/home/index.html.erb
<% content_for :title, "Strona główna" %>
<h1>AdDash</h1>

app/views/home/terms.html.erb
<% content_for :title, "Warunki korzystania z serwisu" %>
<h1>Zasady korzystania z serwisu</h1>
<p>
Tutaj pojawią się zasady korzystania z naszej strony :)
</p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
<div class="container">
<%= link_to 'Zasady korzystania z serwisu', terms_path, class: 'pull-right'%>
<p class="text-muted">Strona utworzona w celu nauki Ruby on Rails</p>
</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "AdDash", root_path, id: "logo", class: "navbar-brand" %>
</div>
<div id="navbar" class="collapse navbar-collapse">
<ul class="nav navbar-nav">
<li><%= link_to "Strona główna", root_path %></li>
<li><%= link_to "Ogłoszenia", ads_path %></li>
<li><%= link_to "O nas", about_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<% if logged_in? %>
<li><%= link_to "Moje konto", account_path %></li>
<li><%= link_to "Wyloguj się", logout_path, method: :delete %></li>
<% else %>
<li><%= link_to "Logowanie", login_path %></li>
<li><%= link_to "Rejestracja", signup_path %></li>
<% end %>
</ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdDash | <%= content_for :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/1200px-Ruby_logo.svg.png" />

    <script src='https://www.google.com/recaptcha/api.js'></script>

  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
  </body>
  </html>

app/views/users/account.html.erb
<% content_for :title, 'Moje konto' %>
<h1>Moje konto</h1>
<h4>Moje dane:</h4>
<div class="row">
<div class="col-md-6">
<table class="table">
<tr>
<th>Email:</th>
<td><%= current_user.email %></td>
</tr>
<tr>
<th>Imię:</th>
<td><%= current_user.first_name %></td>
</tr>
<tr>
<th>Nazwisko:</th>
<td><%= current_user.last_name %></td>
</tr>
</table>
</div>
</div>

app/views/users/new.html.erb
<% content_for :title, 'Rejestracja' %>
<h1>Rejestracja</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@user, url: signup_path) do |f| %>
    <div class="form-group">
      <%= f.label :email, 'Adres email' %>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Wpisz email' %>
      <%= error_message_for(f.object, :email) %>
    </div>

  <div class="form-group">
    <%= f.label :first_name, 'Imię' %>
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'Wpisz imię' %>
    <%= error_message_for(f.object, :first_name) %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, 'Nazwisko' %>
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Wpisz nazwisko' %>
    <%= error_message_for(f.object, :last_name) %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'Hasło' %>
    <%= f.password_field :password, class: 'form-control',
    placeholder: 'Wpisz hasło'%>
    <%= error_message_for(f.object, :password) %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'Potwierdzenie hasła' %>
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Wpisz ponownie hasło' %>
    <%= error_message_for(f.object, :password_confirmation) %>
</div>


  <div class="actions">
    <%= f.submit 'Zarejestruj się', class: 'btn btn-primary' %>
  </div>

  <br />
  <div class="g-recaptcha" data-sitekey="6LdLcjQUAAAAABpwlXWhhZKkMMedTMPEvPJ8KSgg"></div>

  <% end %>


</div>
</div>